### ISSUE TITLE
letter case inconsicency

### ISSUE THREAD

**Issue by Ant1r** [HenriAugusto/easyflow#13]
hi Henri,

easyflow looks cool, but is unusable on a case sensitive OS, because the names of the objects that are instantiated in the help patches are not consistent with the actual filenames.

e.g : on my Linux system, if I open printHere-help patch, I have a bunches of errors such as:
```
 ListPick
... couldn't create

```
because, for instance, ListPick.pd doesn't exist, only listPick.pd does.

**Comment by HenriAugusto** [comment]
Thanks for pointing that out! Once I've renamed all the objects to start with a lowercase but forgot to rename them in the _.pd_ files.

**Comment by HenriAugusto** [comment]
I must have missed the documentation stating that pd abstraction instantiation is tied to the OS! (Actualy, is there this info in the docs? I can't see to find it)

Anyway i wonder how much more windows users are unaware of this! I've wrote a little tcl script to help me find the inconsistencies so i also wonder if that would be of any help to someone else.

I should add a note in the readme for windows users to remember to always use lowerCamelCase (and link to the [pd auto completion plugin](https://github.com/HenriAugusto/completion-plugin) since it can help with that)
